In [14]:
import pandas as pd
import numpy as np
from tqdm import tqdm
from sklearn.preprocessing import normalize

In [6]:
df =  pd.read_csv('data/news_dataset.txt', header=None, sep=" ")

In [7]:
df.head()

0    1    2    3    4    5    6    7    8    9    ...  93   94   95   96   \
0    2    0    5    0    0   37    6    0    0    0  ...    0    1    3    0   
1    8    0    1    3   36    0    0    0    0    0  ...    0    3    0    1   
2    5    0    3    0    0    0    0    0    0    0  ...    0    0    0   23   
3    4    0   77    0    0   13    0    0    0    0  ...    5    0    0    0   
4    2    1   43    0    2   44    1    0    0    0  ...    0    0    0    0   

   97   98   99   100  101  102  
0    0   17   30    4    0  NaN  
1    5    1    0    0   10  NaN  
2    0   11    3    0    0  NaN  
3    2    4    0    0    0  NaN  
4    0    0   13    0    0  NaN  

[5 rows x 103 columns]

In [12]:
df = df.drop([102], axis=1)

In [86]:
normalize(np.random.randint((9,1)), axis=0)

ValueError: Expected 2D array, got 1D array instead:
array=[7. 0.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [96]:
x = [np.random.randint(90, size =(len(df.columns) - 2)) for i in range(0,10)]

In [97]:
arm_context = pd.DataFrame(x)

In [98]:
x[0]

array([70, 51, 79,  0, 56, 10, 68, 49, 24, 77, 71, 76, 34, 41, 60, 36, 52,
       29, 72,  5,  0, 81, 81, 84, 80, 62,  4, 41, 10, 46, 22,  7,  5, 19,
        3, 42, 37, 20, 45, 68, 64, 89, 83, 34, 27, 10,  6, 17, 22,  2, 72,
        5, 59, 19, 36, 18, 78, 20, 82, 65, 27,  7, 76, 73, 31, 36, 19, 29,
       44, 14, 44, 83,  9, 21, 50, 57, 85,  0,  1, 44, 40, 19, 89, 41, 49,
       12, 66, 13,  0, 86,  4, 51,  9, 57, 76, 77, 59, 54, 64, 27])

In [99]:
arm_context.iloc[0]

0     70
1     51
2     79
3      0
4     56
      ..
95    77
96    59
97    54
98    64
99    27
Name: 0, Length: 100, dtype: int64

In [100]:
df.head()

0    1    2    3    4    5    6    7    8    9    ...  92   93   94   95   \
0    2    0    5    0    0   37    6    0    0    0  ...    0    0    1    3   
1    8    0    1    3   36    0    0    0    0    0  ...    0    0    3    0   
2    5    0    3    0    0    0    0    0    0    0  ...    0    0    0    0   
3    4    0   77    0    0   13    0    0    0    0  ...    0    5    0    0   
4    2    1   43    0    2   44    1    0    0    0  ...    0    0    0    0   

   96   97   98   99   100  101  
0    0    0   17   30    4    0  
1    1    5    1    0    0   10  
2   23    0   11    3    0    0  
3    0    2    4    0    0    0  
4    0    0    0   13    0    0  

[5 rows x 102 columns]

In [101]:
arm_context_ = np.zeros((10000, 100))
for i in tqdm(range(0, len(df[0]))):
    arm = df[0][i]
    t = x[arm - 1] 
    arm_context_[i] = t

100%|████████████████████████████████████████████████████████████████████████| 10000/10000 [00:00<00:00, 163936.70it/s]


In [102]:
arm_context_

array([[81., 56.,  1., ..., 46., 67., 67.],
       [24., 33.,  3., ..., 56., 14., 34.],
       [72.,  2., 58., ..., 83., 54., 32.],
       ...,
       [35., 68., 26., ..., 46., 61., 39.],
       [76., 33.,  3., ..., 59., 35.,  7.],
       [76., 33.,  3., ..., 59., 35.,  7.]])

In [103]:
arm_context = pd.DataFrame(arm_context_)

In [104]:
arm_context

0     1     2     3     4     5     6     7     8     9   ...    90  \
0     81.0  56.0   1.0   6.0  15.0  66.0  87.0  66.0  26.0  53.0  ...  31.0   
1     24.0  33.0   3.0  19.0  36.0  57.0  24.0  56.0   4.0  43.0  ...   9.0   
2     72.0   2.0  58.0  69.0  33.0  34.0  59.0   5.0  69.0  82.0  ...  21.0   
3     76.0  33.0   3.0  89.0  69.0  31.0  43.0  37.0  71.0  14.0  ...  56.0   
4     81.0  56.0   1.0   6.0  15.0  66.0  87.0  66.0  26.0  53.0  ...  31.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
9995  70.0  51.0  79.0   0.0  56.0  10.0  68.0  49.0  24.0  77.0  ...   4.0   
9996  81.0  56.0   1.0   6.0  15.0  66.0  87.0  66.0  26.0  53.0  ...  31.0   
9997  35.0  68.0  26.0  15.0   1.0  61.0  16.0   7.0  45.0  59.0  ...  74.0   
9998  76.0  33.0   3.0  89.0  69.0  31.0  43.0  37.0  71.0  14.0  ...  56.0   
9999  76.0  33.0   3.0  89.0  69.0  31.0  43.0  37.0  71.0  14.0  ...  56.0   

        91    92    93    94    95    96    97    98    99  
0     26.0  34.0  22.0  85.0  73.0   7.0  46.0  67.0  67.0  
1     44.0  20.0  50.0   7.0  86.0  46.0  56.0  14.0  34.0  
2     79.0  48.0  32.0  31.0  40.0  57.0  83.0  54.0  32.0  
3     64.0  48.0  86.0  50.0  58.0  25.0  59.0  35.0   7.0  
4     26.0  34.0  22.0  85.0  73.0   7.0  46.0  67.0  67.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
9995  51.0   9.0  57.0  76.0  77.0  59.0  54.0  64.0  27.0  
9996  26.0  34.0  22.0  85.0  73.0   7.0  46.0  67.0  67.0  
9997   3.0  19.0  70.0  38.0  41.0  47.0  46.0  61.0  39.0  
9998  64.0  48.0  86.0  50.0  58.0  25.0  59.0  35.0   7.0  
9999  64.0  48.0  86.0  50.0  58.0  25.0  59.0  35.0   7.0  

[10000 rows x 100 columns]

In [105]:
arm_context_[0]

array([81., 56.,  1.,  6., 15., 66., 87., 66., 26., 53.,  7., 51., 46.,
        9., 54., 22., 63.,  2., 35., 31., 52., 66., 82., 63., 63., 37.,
       37., 52., 46., 86., 50., 48., 54.,  6., 57., 70., 40., 33., 79.,
       44.,  8., 40., 60., 63.,  1.,  5., 78., 88., 48., 34., 78., 43.,
       13., 68., 30., 42., 68., 72., 67.,  0.,  4., 85., 34., 25., 41.,
       31., 27., 28.,  1., 59., 87., 83., 89., 15.,  6.,  3., 70., 74.,
       54., 68., 80.,  1., 59., 46.,  5., 71., 82., 61., 57., 59., 31.,
       26., 34., 22., 85., 73.,  7., 46., 67., 67.])

In [106]:
final_df = pd.concat([df, arm_context], axis=1)
final_df

0   1   2   3   4   5   6   7   8   9   ...    90    91    92    93  \
0      2   0   5   0   0  37   6   0   0   0  ...  31.0  26.0  34.0  22.0   
1      8   0   1   3  36   0   0   0   0   0  ...   9.0  44.0  20.0  50.0   
2      5   0   3   0   0   0   0   0   0   0  ...  21.0  79.0  48.0  32.0   
3      4   0  77   0   0  13   0   0   0   0  ...  56.0  64.0  48.0  86.0   
4      2   1  43   0   2  44   1   0   0   0  ...  31.0  26.0  34.0  22.0   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...   ...   ...   ...   ...   
9995   1   0   0   3  29   0   0   0   0   0  ...   4.0  51.0   9.0  57.0   
9996   2   0   1   0  29   0   0   0   0   0  ...  31.0  26.0  34.0  22.0   
9997   9   1  79   0   0  17   0   0   0   0  ...  74.0   3.0  19.0  70.0   
9998   4   0  29   0   2  44   0   0   0   0  ...  56.0  64.0  48.0  86.0   
9999   4   0   0   2  35   0   0   0   0   0  ...  56.0  64.0  48.0  86.0   

        94    95    96    97    98    99  
0     85.0  73.0   7.0  46.0  67.0  67.0  
1      7.0  86.0  46.0  56.0  14.0  34.0  
2     31.0  40.0  57.0  83.0  54.0  32.0  
3     50.0  58.0  25.0  59.0  35.0   7.0  
4     85.0  73.0   7.0  46.0  67.0  67.0  
...    ...   ...   ...   ...   ...   ...  
9995  76.0  77.0  59.0  54.0  64.0  27.0  
9996  85.0  73.0   7.0  46.0  67.0  67.0  
9997  38.0  41.0  47.0  46.0  61.0  39.0  
9998  50.0  58.0  25.0  59.0  35.0   7.0  
9999  50.0  58.0  25.0  59.0  35.0   7.0  

[10000 rows x 202 columns]

In [107]:
np.savetxt(r'data\news_data_with_arm_context.txt', final_df.values, fmt='%d')

In [114]:
def calculate_projection(u, v):
    v_norm = np.sqrt(sum(v**2))
    proj_on_v = (np.dot(u, v) / v_norm**2) * v
    return proj_on_v

In [119]:
# Open data
data_path = 'data/news_data_with_arm_context.txt'
with open(data_path, "r") as f:

    for line_data in tqdm(f):

        # 1st column: Logged data arm.
        # Integer data type
        data_arm = int(line_data.split()[0])

        # 2nd column: Logged data reward for logged chosen arm
        # Float data type
        data_reward = float(line_data.split()[1])

        # 3rd columns onwards: 100 covariates. Keep in array of dimensions (100,) with float data type
        covariate_string_list = line_data.split()[2:]
        data_x_array = np.array([float(covariate_elem) for covariate_elem in covariate_string_list])
        user_array = data_x_array[:100]
        arm_array = data_x_array[100:]
    #         print(len(user_array))
    #         print(len(arm_array))
        
        x = calculate_projection(user_array,arm_array)
        print(data_x_array.shape)
        print(x.shape)
        break
    


0it [00:00, ?it/s]

(200,)
(100,)
